### ISSUE TITLE
A question about the CV used in the plumed.dat of alanine

### ISSUE THREAD

**Issue by gongshuai0606** [luigibonati/deep-learning-slow-modes#3]
Hi, the line 23 `"ARG=deep.node-1"` in data/ala2-multi/3_opes_multi_dtica/plumed.dat shows that the second output of the network is used as Deep-TICA 1 to enhance the sampling rather than using the first output deep.node-0, but I noticed that the first output seems to correspond to the slow process which is well described by the torsional angles Φ in tutorial/Tutorial.ipynb

**Comment by luigibonati** [comment]
Hi, it was just a matter of how the eigenvalues were sorted. As detailed in the `plumed.dat` file, this is the correspondence between the Deep-TICA CVs obtained in the notebook and the ones loaded in PLUMED:

https://github.com/luigibonati/deep-learning-slow-modes/blob/ddf5d4aec08a995932435f828f6828934476b2f4/data/ala2-multi/3_opes_multi_dtica/plumed.dat#L16-L18

so the mode that is biased to enhance sampling is indeed the slowest mode proportional to Φ. is it clear now?

**Comment by gongshuai0606** [comment]
> Hi, it was just a matter of how the eigenvalues were sorted. As detailed in the `plumed.dat` file, this is the correspondence between the Deep-TICA CVs obtained in the notebook and the ones loaded in PLUMED:
> 
> https://github.com/luigibonati/deep-learning-slow-modes/blob/ddf5d4aec08a995932435f828f6828934476b2f4/data/ala2-multi/3_opes_multi_dtica/plumed.dat#L16-L18
> 
> so the mode that is biased to enhance sampling is indeed the slowest mode proportional to Φ. is it clear now?

Thank you very much. I understand now
